# Проект: Дашборд конверсий

## Импортируем библиотеки

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import plotly.express as px
import requests as rq
from dotenv import load_dotenv
import os
%time

CPU times: total: 0 ns
Wall time: 20 μs

## Статистические расчёты

Выгружаем таблицы с помощью библиотеки **Pandas**

In [72]:
data_v = pd.read_csv('visits_1k.csv')

data_r = pd.read_csv('regs_1k.csv')

Предварительный анализ таблицы visits_1k

In [73]:
data_v.describe()

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

Предварительный анализ таблицы regs_1k

In [74]:
data_r.describe()

            user_id
count  1.000000e+03
mean   4.488623e+06
std    2.620568e+06
min    2.236800e+04
25%    2.235489e+06
50%    4.473044e+06
75%    6.779707e+06
max    8.881772e+06

## Запросы к API

In [41]:
## Запрос данных к visits
df = pd.DataFrame(
    rq.get(
        'https://data-charts-api.hexlet.app/visits',
        params={'begin': '2023-03-01', 'end': '2023-09-01'}
    ).json()
)
print(df)

                                    visit_id platform  \
0       25c1dcbb-cb2d-41dc-88c0-8f5dd8d18483      web
1       b09b2b11-0d64-46a2-954a-d8bcd54b207f      web
2       348148db-9841-4b42-a0e1-7631f4667f83      web
3       65f98235-9667-460c-964e-5604b75b48a1      web
4       9b298132-4992-4dff-9d5b-b8741d3b7870      web
...                                      ...      ...
263454  02f7a75d-2445-49b3-90a5-6e1263187881      ios
263455  2927323a-977d-432a-b470-6b09d7ed3cc5  android
263456  b0f5c075-0008-4631-8cbc-7e86b5bc7f7e      web
263457  f7dea2c9-a5c0-4d71-b6f4-1d2ac7bd9a9c      web
263458  abf8f308-e4fc-428e-a873-ddc41646a440      web

                                               user_agent             datetime
0       Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...  2023-03-01T00:00:43
1       Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...  2023-03-01T00:02:24
2       Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...  2023-03-01T00:03:08
3       Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  2023-03-01T00:03:57
4       Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15....  2023-03-01T00:09:11
...                                                   ...                  ...
263454  Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_3 like...  2023-08-31T23:48:11
263455  Mozilla/5.0 (Linux; Android 10; K) AppleWebKit...  2023-08-31T23:49:17
263456  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  2023-08-31T23:51:27
263457  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  2023-08-31T23:52:48
263458  Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15....  2023-08-31T23:52:57

[263459 rows x 4 columns]

In [42]:
## Запрос данных к registrations
df = pd.DataFrame(
    rq.get(
        'https://data-charts-api.hexlet.app/registrations',
        params={'begin': '2023-03-01', 'end': '2023-09-01'}
    ).json()
)
print(df)

                  datetime                               user_id  \
0      2023-03-01T07:40:13  2e0f6bb8-b029-4f45-a786-2b53990d37f1
1      2023-03-01T13:14:00  f007f97c-9d8b-48b5-af08-119bb8f6d9b6
2      2023-03-01T03:05:50  24ff46ae-32b3-4a74-8f27-7cf0b8f32f15
3      2023-03-01T00:04:47  3e9914e1-5d73-4c23-b25d-b59a3aeb2b60
4      2023-03-01T18:31:52  27f875fc-f8ce-4aeb-8722-0ecb283d0760
...                    ...                                   ...
21831  2023-08-31T07:32:08  a94b4a28-f25c-433c-b4ef-85af7d5b0c11
21832  2023-08-31T23:25:50  fc709c6b-528b-40d8-8980-c2c278e5a628
21833  2023-08-31T19:29:18  11e32805-7571-4108-8e50-e211d051bf7e
21834  2023-08-31T19:38:54  bce7b818-768b-434a-b6af-573cd60bff7f
21835  2023-08-31T08:36:05  fe03e08a-8e86-4b5f-9a50-c18a02b0d234

                            email platform registration_type
0               ebyrd@example.org      web            google
1        knightgerald@example.org      web             email
2      cherylthompson@example.com      web             apple
3           halldavid@example.org      web             email
4            denise86@example.net      web            google
...                           ...      ...               ...
21831         ikelley@example.net      ios             apple
21832     brittanycox@example.net      ios             apple
21833           aryan@example.net      ios             apple
21834       emartinez@example.net      ios             email
21835      terriperry@example.net      ios             email

[21836 rows x 5 columns]